# Generated by Django 5.1.7 on 2025-04-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Idols", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agency",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
