# Generated by Django 5.1.7 on 2025-03-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Idols", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agency",
            name="image_ext",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="agency",
            name="image_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="agency",
            name="image_url",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="image_ext",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="image_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="image_url",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="idol",
            name="image_ext",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="idol",
            name="image_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="idol",
            name="image_url",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
