# Generated by Django 5.1.7 on 2025-03-30 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Idols", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agency",
            name="image",
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="color",
            field=models.CharField(
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="유효한 HEX 색상을 입력하세요.",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="image",
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="sns",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="idol",
            name="image",
            field=models.URLField(max_length=500, null=True),
        ),
    ]
