# Generated by Django 5.1.7 on 2025-03-31 05:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Idols", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="manager",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managed_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="agency",
            name="image",
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="color",
            field=models.CharField(
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="유효한 HEX 색상을 입력하세요.",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="image",
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="sns",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="idol",
            name="image",
            field=models.URLField(max_length=500, null=True),
        ),
    ]
