# Generated by Django 5.1.7 on 2025-03-31 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Idols", "0002_group_manager_alter_agency_image_alter_group_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="color",
            field=models.CharField(
                max_length=7,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="유효한 HEX 색상을 입력하세요.",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="idol",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
