# Generated by Django 5.1.7 on 2025-03-31 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Idols", "0003_alter_group_color_alter_group_image_alter_idol_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="color",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="유효한 HEX 색상을 입력하세요.",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
    ]
