name: Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -P 3306"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      DJANGO_SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: "localhost"
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_HOST: "localhost"
      MYSQL_PORT: "3306"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Install Packages & Libraries
        run: |
          poetry install --no-root

      - name: Create Test Database
        run: |
          mysql -h 127.0.0.1 -P 3306 -uroot -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS test_fav_idol CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;"

      - name: Run Django Migration
        run: |
          poetry run python manage.py migrate

      - name: Run Tests
        run: |
          poetry run python manage.py test
